"""Answer validator for detecting empty outputs, prompt leakage, placeholders, and formatting issues."""

from __future__ import annotations

import re


class AnswerValidator:
    """Validates generated text for quality issues and emits structured warnings."""

    PLACEHOLDER_PATTERNS = [
        r"\bTODO\b",
        r"\bTBD\b",
        r"\[insert\s+[^\]]+\]",
        r"\bplaceholder\b",
        r"\[your\s+answer\s+here\]",
    ]

    PROMPT_LEAKAGE_PATTERNS = [
        r"=== SYSTEM INSTRUCTIONS ===",
        r"=== USER REQUEST & CONTEXT ===",
        r"Answer ONLY using the supplied mathematical context",
        r"Never invent theorems",
    ]

    def validate(self, text: str, context_chunks_count: int = 1) -> list[str]:
        """Inspect generated text and return list of validation warning strings.

        Args:
            text: Post-processed answer string.
            context_chunks_count: Number of context chunks supplied.

        Returns:
            List of warning strings (empty list if no issues found).
        """
        warnings: list[str] = []

        if not text or not text.strip():
            warnings.append("Empty answer text generated by LLM adapter")
            return warnings

        # 1. Check for prompt instruction leakage
        for pattern in self.PROMPT_LEAKAGE_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                warnings.append(f"Prompt instruction leakage detected: '{pattern}'")

        # 2. Check for placeholder tokens
        for pattern in self.PLACEHOLDER_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                warnings.append(f"Placeholder text detected: matching pattern '{pattern}'")

        # 3. Check for minimum length / missing reasoning
        if len(text.strip().split()) < 10:
            warnings.append("Answer is unusually short (< 10 words) and may be missing reasoning steps")

        # 4. Check for missing mathematical content if context had math
        if context_chunks_count > 0 and not any(char in text for char in ["=", "\\", "$", "Theorem", "Definition", "Lemma", "1", "2", "3"]):
            warnings.append("Answer does not reference mathematical statements or notation from context")

        return warnings
